### ISSUE TITLE
dotnet build fails when the task project has dependencies

### ISSUE THREAD

**Issue by BalassaMarton** [natemcmaster/blog#3]
I've cloned your repo to demonstrate the issue:
https://github.com/BalassaMarton/msbuild-tasks
The only thing I changed is that it now has a dependency on `Newtonsoft.Json` and creates a `JObject` to make sure that the dependency is loaded. 
`dotnet build` generates the following error:
```
The "SayHello" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. [...]
File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
at MSBuildTasks.SayHello.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()
```

I've event toyed around with copying the dependencies to the `tasks` directory, but nothing worked. Any suggestion why this might happen? I have a small project [`MSBump`](https://github.com/BalassaMarton/MSBump) that I'm trying to port to .NET Standard, but without success.

**Comment by BalassaMarton** [comment]
After some more experimenting, it looks like the `Newtonsoft.Json` dependency is causing this error, not just any dependency. But it is still unclear where to look for the problem, since `Newtonsoft.Json` targets both `netstandard` and `net45`.

**Comment by natemcmaster** [comment]
This is a great question, one I've received a few times. MSBuild tasks with assembly dependencies introduce a new level of complexity. I haven't addresses this one quite yet in my material, but this has been asked enough that I'm considering writing a detailed post on this subject.

In the meantime, checkout this answer to the same question: https://stackoverflow.com/a/45750930/2526265. In a nutshell, you need Newtonsoft.Json.dll in the folder next to your task assembly.

**Comment by BalassaMarton** [comment]
I got this error after copying the dlls next to the task dll. However, I've downgraded to the `9.x` version of `Newtonsoft.Json` and now it works perfectly, so it's probably something with the dependencies of this package.

**Comment by natemcmaster** [comment]
@BalassaMarton took me a while to get this, but finally wrote up my thoughts on tasks with dependencies. See http://www.natemcmaster.com/blog/2017/11/11/msbuild-task-with-dependencies/

**Comment by BalassaMarton** [comment]
Nice article @natemcmaster
