### ISSUE TITLE
Unable reference task directly with Sdk="Microsoft.NET.Sdk.Web" attribute in Project element

### ISSUE THREAD

**Issue by jsacapdev** [natemcmaster/blog#4]
I refer to my test github repository https://github.com/jsacapdev/msbuild-tasks.git, that aids my understanding of your blog posts.

In my test projects, if I dont have the Sdk="Microsoft.NET.Sdk.Web" attribute, I can reference the task directly. If this attribute is present, I can only get it to work via the NuGet package.

In Visual Studio Code, in my Web API project (https://github.com/jsacapdev/msbuild-tasks/blob/master/test/Example.Web.Api/Example.Web.Api.csproj) I cannot refer to a task directly in the *.csproj, only if I reference it via the NuGet package of my task.

I do have a direct reference to the task in another *.csproj (https://github.com/jsacapdev/msbuild-tasks/blob/master/test/MsBuildTasks.Test/MsBuildTasks.Test.csproj), that I can get to work but I need to have a empty Project element.

So the question is - how can I refer to a task in a seperate library if I am using a Web API *.csproj (with an element Project Sdk="Microsoft.NET.Sdk.Web")? Ideally, step into it aswell by attaching to process. There may be something wrong in my code, but I cant get this to work. Even with the Channel 9 samples (Video 1) the demo code seem to have a *.csproj with a empty Project. Does that mean that if you want to use a task in a Web API project, it needs to be packaged up as a NuGet package?

**Comment by natemcmaster** [comment]
To make sure I understand correctly, you're trying to use an MSBuild task by adding a ProjectReference to the project that creates it, right? i.e. you want your WebAPI project to look like this?
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <!-- other stuff -->
  <ItemGroup>
     <ProjectReference Include="..\MyTasks\MyTasks.csproj" />
  </ItemGroup>
</Project>
```

If I understood right, I'm sorry to say it won't be that simple. PackageReference is not equivalent to ProjectReference. If you want to use an MSBuild task from a local project, you would instead need to so something like this:

1. Ensure MyTasks.csproj is compiled first. You'll need to compile it in a separate process from one compiling your web project. MSBuild can't load a task assembly that doesn't exist yet.
2. Use UsingTask with a file location.
3. Import your targets file into the web project.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <!-- other stuff -->
  <UsingTask TaskName="MyTasks.Banana" AssemblyFile="..\MyTasks\MyTasks\bin\Debug\netstandard1.6\MyTasks.dll" />
  <Import Project="..\MyTasks\MyTasks\build\MyTasks.targets" />
</Project>

**Comment by jsacapdev** [comment]
that is awesome. thanks for the guidance.
