### ISSUE TITLE
NuGet package does not contain 'tools' folder on pack

### ISSUE THREAD

**Issue by jsacapdev** [natemcmaster/blog#5]
Following your post:

http://www.natemcmaster.com/blog/2017/11/11/build-tools-in-nuget/

When I attempt to run the following command:

`dotnet pack MyTypescriptGenerator.csproj --output ./ --configuration Release`

And then examine the Nu Get package there is no 'tools' sub-folder.

I can see the console app has been published to ./bin/release/publish/... but it does not seem to be making it into the Nu Get package.

My own repo:

https://github.com/jsacapdev/NuGetNetBuildTools

```
C:\playground\NuGetNetBuildTools\src\MyTypescriptGenerator>dotnet --info
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

**Comment by natemcmaster** [comment]
Thanks for the repro. Looks like my sample missed at least on important piece, and didn't account for some issues in nuspec. I'll update the blog post, and opened https://github.com/jsacapdev/NuGetNetBuildTools/pull/1 in your sample.
