### ISSUE TITLE
CV template

### ISSUE THREAD

**Issue by tom031** [natemcmaster/blog#7]
Hi Nate,
I visited your website and I love with your cv style, it look so clean. Was it created by latex, could you please share you cv template?. It will very helpful for my job hunt.
Thank you

**Comment by natemcmaster** [comment]
I made it with this [Resume-2016.docx](https://github.com/natemcmaster/blog/files/1644992/Resume-2016.docx). I used the [Gotham](https://www.typography.com/fonts/gotham/overview/) typeface, which isn't free, so your version may look different. But there are plenty of sans-serif options that look similar enough that you can probably get the same effect.

Good luck on the job hunt!
-Nate
