### ISSUE TITLE
Feed hard to discover

### ISSUE THREAD

**Issue by bricelam** [natemcmaster/blog#8]
Add `<link rel="alternate" />` tag in `<head>` to your feed.xml the help RSS readers find your feed. For, you know, the one other person besides me that still uses an RSS reader. 😉

**Comment by bricelam** [comment]
P.S. I like the [jekyll-feed](https://github.com/jekyll/jekyll-feed) plugin better than the template's default `feed.xml`

**Comment by natemcmaster** [comment]
awesome, thanks for the pointer. Added it to my site
